use_gpu: True
device: 0
early_stop:
  patience: 20
  improve_indicator_mode: mean
  the_smaller_the_better: False
federate:
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 300
  share_local_model: False
  client_num: 13
data:
  root: data/
  type: cikmcup
  batch_size: 64
  num_workers: 2
model:
  type: gin
  hidden: 64
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']
  K: 13
train:
  batch_or_epoch: epoch
  local_update_steps: 10
  optimizer:
    weight_decay: 0.0005
    type: SGD
    lr: 0.0001
trainer:
  type: graphminibatch_trainer
eval:
  freq: 5
  metrics: ['imp_ratio']
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  base: 0.
